name: Build and Package JAR

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: maze

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-jar
        path: maze/target/*.jar
